'use client'

import { Jost } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import SideBar from "./components/sidebar";
import "./globals.css";
import { useRouter } from "next/navigation";
import SignIn from "./(auth)/sign-in/page";

const inter = Jost({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex ${inter.className} bg-background`}>
        {children}
      </body>
    </html>
  );
}
